pipeline {
    agent any

    stages {
        stage('Clone repo') {
            steps {
                echo 'Cloning the repo...'
                // Git is skipped for now because you’re running locally
            }
        }

        stage('Set up Python env') {
            steps {
                sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source venv/bin/activate
                    pytest tests/
                '''
            }
        }
    }
}
